### ISSUE TITLE
vtimer_msg crashes after some time - unless there is a delay between msg_receive(&m); and accessing m

### ISSUE THREAD

**Issue by benpicco** [RIOT-OS/RIOT#1811]
Now this one had me puzzled for quite a bit.
On ek-tm4c123gxl tests/vtimer_msg crashes after ~53s - that is, just to make debugging even more confusing, shortly after the hardware timer overflows for the first time.
It also crashes on native after 10s, but I know that native isn't quite as stable, so I disregarded that.

Now when adding a short delay after `msg_receive(&m);` in `timer_thread`, the crash goes away:

```
--- vtimer_msg/main.c	2014-10-10 20:23:59.876720869 +0200
+++ vtimer_msg/main.c	2014-10-13 23:14:48.024480356 +0200
@@ -26,6 +26,8 @@
 #include "thread.h"
 #include "msg.h"
 
+#include "board.h"
+
 char timer_stack[KERNEL_CONF_STACKSIZE_MAIN];
 char timer_stack_local[KERNEL_CONF_STACKSIZE_MAIN];
 
@@ -55,6 +57,11 @@
     while (1) {
         msg_t m;
         msg_receive(&m);
+
+        for (int i = 0; i < 10000; ++i) 
+          GREEN_LED_TOGGLE;
+
+//        puts("message received");
         struct timer_msg *tmsg = (struct timer_msg *) m.content.ptr;
         vtimer_now(&now);
         printf("now=%" PRIu32 ":%" PRIu32 " -> every %" PRIu32 ".%" PRIu32 "s: %s\n",
```

**Comment by authmillenon** [comment]
Is this issue fixed by now?

**Comment by benpicco** [comment]
It's still broken on `native` - although in a different way now:

```
kernel_init(): This is RIOT! (Version: 2014.12-875-gdbd44)
kernel_init(): jumping into first task...
This is thread 3
sending 1st msg
now=0:116 -> every 2.0s: Hello World <-- this is a lie
sending 2nd msg
now=0:127 -> every 5.0s: This is a Test <-- this is a lie
This is thread 4
sec=1 min=0 hour=0
sec=2 min=0 hour=0
sec=3 min=0 hour=0
```

**Comment by noshky** [comment]
Please note that the ``timer_thread`` in the ``main`` has changed, so that messages don't get re-sent. If you add
``vtimer_set_msg(&tmsg->timer, tmsg->interval, thread_getpid(), MSG_TIMER, tmsg);``
to the end of the while loop, the faulty behaviour will be restored. (Hang after 21 seconds on my machine, which is Intel(R) Core(TM)2 Duo CPU     E6750  @ 2.66GHz and Ubuntu 14.04.2 LTS).

**Comment by kaspar030** [comment]
I just checked native, it doesn't crash anymore. Also, as vtimer got kicked out, this is now using vtimer_compat and thus xtimer. So I'll close this as solved.
