### ISSUE TITLE
boards/nucleo-l1: hard faults with shell?

### ISSUE THREAD

**Issue by PeterKietzmann** [RIOT-OS/RIOT#6484]
Running e.g. tests/shell, examples/default or examples/gnrc_networking on a nucelo-l1 hard-faults. I didn't check other nucleo boards nor did I look into details

**Comment by haukepetersen** [comment]
Other nucleo boards seem to be fine, but run into the same hard-fault on the l1. Seems to me, that something is broken with the UART interrupt, looking into it now.

**Comment by haukepetersen** [comment]
hm, seems like we get hardfaults on any interrupt -> the `xtimer_msg` test reboots every second...

**Comment by haukepetersen** [comment]
this is getting creepy: `tests/periph_timer` works as expected. `xtimer_msg` and `xtimer_usleep` work fine with `DEVELHELP` enabled, but hard fault once `DEVELHELP` is disabled...

**Comment by haukepetersen** [comment]
one step closer: git bisect lead me to `807a190e2086793225e774a5d64983467cf221b7` (cpu: cortexm: adapt to periph/pm) as the bad commit. Strange.

**Comment by haukepetersen** [comment]
hmm, setting, or better waking up the CPU from sleep, is the problem here. So what is the L1 doing (or not doing), so it crashes when sleeping?!

**Comment by haukepetersen** [comment]
fixed by #6499

**Comment by PeterKietzmann** [comment]
#6499 was merged

**Comment by kYc0o** [comment]
I think a regression of this bug came back after #7385 was merged. Should we reopen this one or keep going on #8024 ?
